## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost/postgres
  jpa:
    show-sql: false
#    generate-ddl: false
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: taconovisad@gmail.com
    password: spgr nlaw qind ptmw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #      dialect: org.hibernate.dialect.MySQL5Dialect

#  jackson:
#    default-property-inclusion: non_null
#  redis:
#    host: localhost
#    port: 6379
#  freemarker:
#      cache: false




  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
  sql:
    init:
      continue-on-error: true
      mode: always
      platform: postgres
server:
  servlet:
    contextPath: /api
  port: 8080

jwtSecret: me.zhulin
jwtExpiration: 86400



